<div class="account1">
    
    <div class="carre">
    <h1>Historique des parties</h1>
    <?php foreach($infos as $info): ?>
    <p>Vous avez eu comme résultat : <strong><?= $info ['result'] ?></strong> le <?= $info ['date'] ?></p>
    <?php endforeach ?>
    
    </div>
    
    <h2>Changer de mot de passe</h2>
    
    <form method="POST">
        <label for="motDePasseActuel">Mot de passe actuel</label>
        <input type="password" name="motDePasseActuel" id="motDePasseActuel" required/>
        
        <label for="passwordChange">Nouveau mot de passe</label>
        <input type="password" name="passwordChange" id="passwordChange" required/>
        
        <p>Votre mot de passe doit contenir au moins 12 lettres, 1 majuscule,<br> 1 minuscule, 1 chiffre et 1 caratère spécial</p>
        
        <button type="submit" name="envoyerMDP">Changer de mot de passe</button>
        
    </form>
    
    <form method="POST">
    <button class="red" type="submit" name="delete_account">Supprimer mon compte</button>
    </form>
</div>