<div>
    <h1>Historique des parties</h1>
    <?php foreach($infos as $info): ?>
    <p>Vous avez eu comme résultat : <strong><?= $info ['result'] ?></strong> le <?= $info ['date'] ?></p>
    <?php endforeach ?>
    
    <a class="Jouer" href="quiz.php">Jouer</a>
    
    <h2>Changer de mot de passe</h2>
    
    <form method="POST">
        <label for="motDePasseActuel">Mot de passe actuel</label>
        <input type="password" name="motDePasseActuel" id="motDePasseActuel" required/>
        
        <label for="passwordChange">Nouveau mot de passe</label>
        <input type="password" name="passwordChange" id="passwordChange" required/>
        
        <button type="submit" name="envoyerMDP">Changer de mot de passe</button>
        
    </form>
    
    <form method="POST">
    <button type="submit" name="delete_account">Supprimer mon compte</button>
    </form>
</div>