<div class="main">

<div class="container">
    <h1>Connexion</h1>
    
    <?php if(isset($error)): ?>
        <div class="error"><?= $error ?></div>
    <?php endif; ?>

    <form method="post" action="connexion.php">
        
            <label for="email">Email</label>
            <input type="text" id="email" name="email" required>
        
        
        
            <label for="password">Mot de passe</label>
            <input type="password" id="password" name="password" required>
        
        
        <button type="submit">Se connecter</button>
    </form>
    
    <p>Pas encore de compte ? <a class="signup1" href="signup.php">S'inscrire</a></p>
</div>

</div>