<div>
    
    
    <h1>Akinator - One Piece</h1>
    <img src="images/OnePieceLogo.png" alt="One piece Logo">
    
    
    <div class="button-container">
    <button type="submit">
    <?php if(isset($_SESSION['user']) && !empty($_SESSION['user'])): ?>
        <a href="quiz.php">Commencer le jeu</a>
    <?php else: ?>
        <a href="connexion.php">Connectez-vous</a>
    <?php endif; ?>
        
        
    </button>
    
    </div>
    
</div>