<div>
    
    <h1>Bienvenue
    <?php if (isset($_SESSION['user']) && !empty($_SESSION['user'])): ?>
        <?= htmlspecialchars($_SESSION['user']) ?>
    <?php endif; ?>
    sur Aki D Nator</h1>
    
    <div class="container">
    <img class="imgGenie" src="images/AkiDNator1.png" alt="AkiDnatorLogo">
    
    
    <div class="button-container">
        
    <button type="submit">
    <?php if(isset($_SESSION['user']) && !empty($_SESSION['user'])): ?>
        <a href="quiz.php">Commencer le jeu</a>
    <?php else: ?>
        <a href="connexion.php">Connectez-vous</a>
    <?php endif; ?>
        
        
    </button>
    
    </div>
    </div>
</div>