<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/0a4bedb4d5.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="style.css">

    <title>Gestionnaire des tâches</title>
</head>

<body>
    
    <header>
        <div class="header">
            
            <nav>
            <div>
            <p><a href="index.php">Akinator</a></p>
            </div>
            
            <div>
                <ul>
                    <li class="connexion"><a href="connexion.php">Connexion</a></li>
                    <li class="inscription"><a href="signup.php">Inscription</a></li>
                    <li class="deconnexion"><a href="logout.php"<i class="fa-solid fa-right-from-bracket"></a>></li>
                </ul>
            </div>
            
            
            
            </nav>
        </div>
        
    </header>
    
    <main>
       
        <?php include "$template.phtml" ?>
        
        
    </main>
    
    <footer>
            <p class="footer">
                @2025 - 3W Academy
            </p>
        </footer>
</body>

</html>