<div class = "main">


<div class="signup">
    
    <h1>Inscription</h1>
    
    <div class="container">
        
        <form method="post">
            
            <label for="name">Nom :</label>
            <input type="text" id="name" name="name" required>
            
            <label for="email">Email :</label>
            <input type="text" id="email" name="email" required>
    
            <label for="new-password">Mot de passe :</label>
            <input type="password" id="new-password" name="password" required>
            
            <p>Votre mot de passe doit contenir au moins 12 lettres, 1 majuscule,<br> 1 minuscule, 1 chiffre et 1 caratère spécial</p>
    
            <button>S'inscrire</button>
            
            <p>Vous avez déjà un compte ? <a href="connexion.php" class="connect"><strong>Se connecter</strong></a> </p>
        </form>
        
    </div>
</div>

</div>
    